on: [push, pull_request]
name: Build native
jobs:
  build_native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup show
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
