on: [push, pull_request]
name: Build web
jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup show
      - run: wget -qO- https://github.com/thedodd/trunk/releases/download/0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - run: trunk build --release
