on: [push, pull_request]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup show
      - uses: actions-rs/clippy-check@v1
        with:
          args: --all-targets
          token: ${{ secrets.GITHUB_TOKEN }}
