on: [push, pull_request]
name: Clippy
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libasound2-dev
      - uses: actions/checkout@v2
      - run: rustup show
      - uses: actions-rs/clippy-check@v1
        with:
          args: --all-targets
          token: ${{ secrets.GITHUB_TOKEN }}
